### ISSUE TITLE
List aliases command

### ISSUE THREAD

**Issue by jodrell2000** [jodrell2000/DaManagement#139]
we need some way to list all available aliases for a given command. We really don't want all the aliases appearing in the normal command list or it'll get too long really fast

------------
Command...
/listAlias dice

Outputs...
The command /dice now has aliases /roll and /yahtzee
or
The command /dice has no aliases

------------
Command...
/listAlias roll

Outputs...
roll is an alias for the command /dice which also the following aliases /yahtzee
or
roll does not exist either as a command or an alias

**Comment by 1hitsong** [comment]
This can be closed.
